### ISSUE TITLE
Test for multiple types

### ISSUE THREAD

**Issue by mcshaman** [josdejong/ducktype#2]
I really love this library @josdejong. I have not used it fully yet but it looks so neat and simple. I'm curious if you still use it yourself or if you have moved on to another way to test types at runtime.

Anyway, I was wondering if there is a way to test if a property is either one type or another?'

```
var person = ducktype({
  name: String,
  dateOfBirth: ducktype([String, Date], {optional: true})
});
```

**Comment by josdejong** [comment]
Thanks, good to hear you like it :)

You should be able to create a type check "String OR Date" like 

```js
var stringOrDate = ducktype(String, Date, {optional: true});
```
Is that what you mean?

See docs: https://github.com/josdejong/ducktype#combined-types

**Comment by mcshaman** [comment]
Thats fantastic! Thanks @josdejong

**Comment by josdejong** [comment]
:+1:
