### ISSUE TITLE
default ducktype object already initialized

### ISSUE THREAD

**Issue by jdmg94** [josdejong/ducktype#4]
the default object that's imported from the lib is apparently initialized already when it reaches the user.
<img width="781" alt="screen shot 2018-02-18 at 3 28 44 pm" src="https://user-images.githubusercontent.com/4754734/36357215-7e68d6f6-14c0-11e8-9d88-df7b725f3a57.png">

**Comment by josdejong** [comment]
Thanks for reporting @jdmg94 . The issue isn't entirely clear to me, can you elaborate? How can I reproduce this issue?
